;
; File generated by cc65 v 2.18 - Git bf4b195
;
	.fopt		compiler,"cc65 v 2.18 - Git bf4b195"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_spiBegin
	.import		_spiEnd
	.import		_spiWrite
	.import		_spiRead
	.export		_gd_putc
	.export		_gd_backc
	.export		_gd_getc
	.import		_wait
	.import		_wait_s

; ---------------------------------------------------------------
; void __near__ __fastcall__ gd_putc (char c)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gd_putc: near

.segment	"CODE"

	jsr     pusha
	jsr     _spiBegin
	lda     #$80
	jsr     _spiWrite
	lda     #$00
	jsr     _spiWrite
	ldy     #$00
	lda     (sp),y
	jsr     _spiWrite
	jsr     _spiEnd
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ gd_backc (int i)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gd_backc: near

.segment	"CODE"

	jsr     pushax
	jsr     _spiBegin
	lda     #$A8
	jsr     _spiWrite
	lda     #$0E
	jsr     _spiWrite
	ldy     #$00
	lda     (sp),y
	jsr     _spiWrite
	jsr     _spiEnd
	jsr     _wait
	jsr     _spiBegin
	lda     #$A8
	jsr     _spiWrite
	lda     #$0F
	jsr     _spiWrite
	lda     #$70
	jsr     _spiWrite
	jsr     _spiEnd
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; char __near__ __fastcall__ gd_getc (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gd_getc: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     _spiBegin
	lda     #$00
	jsr     _spiWrite
	lda     #$00
	jsr     _spiWrite
	jsr     _wait_s
	jsr     _spiRead
	ldy     #$00
	sta     (sp),y
	jsr     _spiEnd
	ldy     #$00
	lda     (sp),y
	lsr     a
	ldx     #$00
	jmp     incsp1

.endproc

