;
; File generated by cc65 v 2.18 - Git bf4b195
;
	.fopt		compiler,"cc65 v 2.18 - Git bf4b195"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_acia_init
	.import		_acia_puts
	.import		_acia_put_newline
	.import		_switch_bank
	.import		_wait
	.export		_i
	.export		_main

.segment	"DATA"

_i:
	.word	$0000

.segment	"RODATA"

S0002:
	.byte	$41,$20,$6D,$69,$6D,$6F,$63,$68,$6F,$64,$65,$6D,$20,$43,$20,$6A
	.byte	$65,$20,$66,$61,$6A,$6E,$20,$6A,$61,$7A,$79,$6B,$20,$3A,$44,$00
S0001:
	.byte	$41,$68,$6F,$6A,$20,$73,$76,$65,$74,$65,$2C,$20,$6A,$61,$20,$6A
	.byte	$73,$65,$6D,$20,$50,$72,$6F,$6A,$65,$6B,$74,$36,$35,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _acia_init
	jsr     _wait
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _acia_puts
	jsr     _acia_put_newline
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _acia_puts
L0002:	inc     _i
	bne     L0005
	inc     _i+1
L0005:	jsr     _wait
	lda     _i
	ldx     _i+1
	jsr     _switch_bank
	lda     _i+1
	bne     L0002
	lda     _i
	cmp     #$FA
	bne     L0002
	lda     #$00
	sta     _i
	sta     _i+1
	jmp     L0002

.endproc

