;
; File generated by cc65 v 2.18 - Git bf4b195
;
	.fopt		compiler,"cc65 v 2.18 - Git bf4b195"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_switch_bank
	.import		_wait
	.export		_i
	.export		_main

.segment	"DATA"

_i:
	.word	$0000

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

L0002:	inc     _i
	bne     L0005
	inc     _i+1
L0005:	jsr     _wait
	lda     _i
	ldx     _i+1
	jsr     _switch_bank
	lda     _i+1
	bne     L0002
	lda     _i
	cmp     #$FA
	bne     L0002
	stz     _i
	stz     _i+1
	bra     L0002

.endproc

